config/routes.rb
Communitymarket::Application.routes.draw do
  resources :schools

  resources :dresses

  resources :messages

  match "/404", to: "exceptions#not_found", via: [:get, :post]
 
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  get '/auth/stripe_connect/callback', to: 'stripe_connect#create'

  resources :email_settings
  resources :followships
  
  
  

  
  resources :transactions do
    collection do
      post :customer_purchase
    end
  end
  resources :memberships do
    collection do
      put :update_individual
      post :join
    end
  end
  resources :followships do
    collection do
      post :follow
    end
  end
  resources :tags

  resources :users do
    collection do
      get :new_modal
    end
    resources :posts
    resources :groups
  end
  resources :pages do
    collection do
      get :dorm_furniture
      get :school_select
    end
  end
  
  
  resources :images
  resources :group_categories
  resources :post_categories
  resources :groups do
    collection do
      put :bulk_update
      put :private
    end
  end

  resources :posts do
    collection do
      get :sort_name
    end
    member do
      get :deactivate
      get :reactivate
      get :complete
      get :undo_completed
    end
    resources :assignments
  end
  
  match '/textbooks', to: "pages#textbooks"
  match '/admin', to: "pages#admin"
  match '/feed', :to =>"pages#feed"
  match '/bulk_update', :to => "groups#bulk_update"
  match '/for_sale', :to => "pages#for_sale"
  match '/borrow_rent', :to => "pages#borrow_rent"
  match '/services', to: "pages#services"
  match '/wanted', :to => "pages#wanted"
  match '/transactions/customer_purchase', :to => "transactions#customer_purchase"
  match '/memberships/join', :to => "memberships#join"
  match '/followships/follow', :to => "followships#join"
  match '/followships/leave', :to => "followships#leave", :via => :delete
  match '/groups/nearby', :to => "groups#nearby"
  match '/search', :to => 'search#index'
  match '/search_tags', :to => 'tags#search'
  match '/about', :to => 'pages#about'
  match '/jobs', to: 'pages#jobs'
  match '/landing', :to => 'pages#landing'
  match '/marketplace', to: 'pages#marketplace'
  match '/invites', :to => 'invites#new', via: :post
  match '/contacts', :to => 'contacts#new', via: :post

  mount CommunityMarket::API =>'/'
  get "/docs" => 'docs#index'

  root :to => 'pages#index'
  
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  extend ::Geocoder::Model::ActiveRecord
  geocoded_by :zipcode
  after_validation :geocode, :if => :zipcode_changed?
  attr_accessible :description, :group_category, :name, :school_id, :group_category_id, :user_id, :member_ids, :private, :longitude, :latitude, :zipcode, :password, :image, :assets_attributes
  #acts_as_mappable :auto_geocode=>{:field=>:zipcode, :error_message=>'Could not geocode address'}
  # geocoded_by :full_street_address   # can also be an IP address
  
  reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode  # auto-fetch address
  
  
  has_many :assets, :as => :imageable, :dependent => :destroy


  accepts_nested_attributes_for :assets
  has_many :memberships, :dependent => :destroy, :foreign_key => :group_id
  has_many :members,    :through => :memberships, :source => :member, :foreign_key => :member_id
  belongs_to :owner,    :class_name => "User", :foreign_key => :user_id
  belongs_to :group_category
  has_many :assignments
  belongs_to :school
  has_many :posts,      :through => :assignments
  
  validates :name, :presence => true
  
  def self.searchable_columns
    wanted_columns = ['name', 'created_at']
    self.column_names.select{ |column| wanted_columns.include?(column) }
  end
  def self.translated_searchable_columns
    columns = self.searchable_columns
    result = columns.map{ |column| [Group.human_attribute_name(column.to_sym), column] }
    result
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    if params[:zipcode]
      zipcode = params[:zipcode]
      @groups = Group.near(zipcode, 1000)
    else
      @groups = filter_groups(Group.all, current_user)
    end
    @g_categories = GroupCategory.all
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.js #index.js.erb
    #   format.json { render json: @groups }
    # end
    # 
    
    @group_attributes = Group.columns
     if params[:sort]
       @groups= Group.order(params[:sort])
     else
       @groups = filter_groups(Group.order(:name), current_user)
     end 

     respond_to do |format|
       format.html # index.html.erb
       format.js # index.js.erb
       format.json { render json: @groups }
     end 
    
  end
  
  def bulk_update
    Membership.where(:id => params[:delete]).destroy_all
    @group = Group.find(params[:group_id])
    respond_to do |format|
      format.html { redirect_to @group }
      format.json { head :no_content }
    end
  end
  
  def bulk_groups_update
    Membership.where(:id => params[:delete]).destroy_all
    @group = Group.find(params[:group_id])
    respond_to do |format|
      format.html { redirect_to @group }
      format.json { head :no_content }
    end
  end 
  
  
  # def nearby
  #     zipcode = 
  #     
  #     
  #     @g_categories = GroupCategory.all
  #     respond_to do |format|
  #       #format.html
  #       format.json  { render :json => @groups }
  #       #format.json { render :json => {:bathrooms => @bathrooms} }
  #       format.js   { render :nothing => true } 
  #      end        
  #   end
    
  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    @posts = filter_posts(@group.posts).sort { |x,y| y.created_at <=> x.created_at }
    @posts = kaminari_paginate(@posts, 50)
    
    @random_groups = Group.last(20) - @user.groups_as_member
    if !signed_in?
      @user = User.new
    else
      @user = current_user
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    
    @group = Group.new
    @categories = GroupCategory.all
    @group.assets.build
    @assets = @group.assets
    @school = School.find(current_user.school_id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    @group.assets.build
    @assets = @group.assets
    @categories = GroupCategory.all
  end

  # POST /groups
  # POST /groups.json
  def create
    ip = request.location
    @user = current_user
    @group = @user.groups_as_owner.new(params[:group])
    params[:group][:member_ids] = (params[:group][:member_ids] << @group.member_ids).flatten
    @group.school_id = @user.school_id
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    params[:group][:member_ids] = (params[:group][:member_ids] << @group.member_ids).flatten

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to root_path }
        format.js
        # format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        #         format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # NEEDS SUCCESS MESSAGE
  def private
    @group = Group.find(params[:group_id])
    params[:group][:member_ids] = (params[:group][:member_ids] << @group.member_ids).flatten
    
    respond_to do |format|
      if params[:password] == @group.password && @group.update_attributes(params[:group])
        flash[:success] = "Successfully joined #{@group.name}"
        format.html { redirect_to root_path }
        format.js
        # format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        #         format.json { head :no_content }
      else
        if params[:password] != @group.password
          flash.now[:wrong_password] = "Wrong Password"
        end
        format.html { render action: "show"}
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
  
  private
  def kaminari_paginate(posts, per_page)
    Kaminari.paginate_array(posts).page(params[:page]).per(per_page)
  end
  
  def filter_groups(groups, user)
    groups = groups.select do |group|
      if groups.nil? || user.nil?
        true
      else
        case      
        when group.school_id != user.school_id
          false
        else
          true
        end
      end
    end
  end

  def filter_posts(posts)
    posts = posts.select do |post|
      case
      when post.active?
        true
      when !post.active? && post.completed?
        true
      else
        false
      end
    end
    return posts
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group, :html =>{:class => "form"} do |f|
  =hidden_field_tag('group[member_ids][]', current_user.id)
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  
  %div.form-group   
    = f.label :name, :class => "control-label"
    = f.text_field :name, type: "text", :class => "form-control", :placeholder => "Group Name"

  %div.form-group   
    = f.label :description, :class => "control-label"
    %div.controls
      = f.text_area :description, type: "text", :rows => "5", :class => "form-control", :placeholder => "Description of Group"


  .row
  
    .col-lg-6
      = f.collection_select(:group_category_id, GroupCategory.all, :id, :name, {:prompt => 'Group Type'},:class => "form-control")
  %br/
  
  %div.form-group
    =f.label :zipcode, :class => "control-label"
    %div.controls
      .col-lg-3.no-left-padding
        =f.text_field :zipcode, type: "text", :class => "form-control", :placeholder => "03755"

  %br/
  %br/
  %br/
  %p.bold Optional:
  = f.label :private, :class => "checkbox" do
    = f.check_box :private,:class => "checkbox", :id => "private"
    =label_tag "Private"
  %div.form-group
    =f.label :password, "Pass-phrase to get into group", :class => "control-label"
    %div.controls
      .col-lg-5.no-left-padding
        = f.text_field :password, type: "text", :class => "form-control", :placeholder => "Password", :disabled => !@group.new_record? && @group.password? ? false : true, :id => "private_group"
          
  
  %br/
  %br/
  %br/     
  /PHOTO UPLOAD FIELDS        
  %div.row
    %div.col-lg-8
      -@assets.each do |asset|
        =f.fields_for :assets, asset do |asset_fields|
          -if asset_fields.object.image_file_name.nil?
            %div.form-group
              =asset_fields.label "image", :class=>"control-label"
              %div.controls
                =asset_fields.file_field :image
          -else
            /= asset_fields.check_box asset_fields.file_field :image_delete, :label => 'Delete Image'
            =image_tag(asset_fields.object.image.url(:post))
            =asset_fields.label  "delete image"
            =asset_fields.check_box :_destroy
          
          
          
  = f.submit 'Save', :class => "btn btn-primary submit-button"

app/views/groups/_group.html.haml
%div.row.group-feed-item
  %div.image.col-lg-2
    =link_to image_tag(group.assets.empty?  ? '/assets/small.png': group.assets.first.image.url(:small), :alt => group.name), group_url(group)
  .feed_item
    .col-lg-7
      = link_to group.name, group_url(group), class: "feed-title"
      .description
        = truncate(group.description, 10)
    .col-lg-2
      = render "shared/simple_join", :group => group

app/views/groups/_group_list.html.haml
=render @groups, :as => "group_feed_item"

app/views/groups/_invite.html.haml
=form_tag "/invites",  :method => :post do
  =hidden_field_tag :from, current_user.id
  =hidden_field_tag :group_id, group.id
  %div.row-fluid
    / =label_tag "paste emails here, even straight out of mail"
    =text_area_tag :content, params[:content], :class => "input-block-level", :placeholder => "Paste emails here", :rows => "10"
  =submit_tag "invite users"

app/views/groups/_join_form.html.haml
/MODAL ATTEMPT
-if current_user
  -if group.members.include?(current_user)
    /=render :partial => "leave"
    = form_for current_user.memberships.find_by_group_id(group), html: { :method => :delete }, remote: true do |f|                                            
      = f.submit "Leave", class: "btn btn-mini"
    /=link_to "Leave", membership_url(current_user.memberships.find_by_group_id(group)), :method => :delete, :confirm => "Are you sure?"
  -else

    -if group.private?
      =form_tag(private_groups_path,  method: :put) do
        =hidden_field_tag :group_id, group.id
        =hidden_field_tag('group[member_ids][]', current_user.id)
        %div.col-lg-3
          =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
        =submit_tag "Join", :class => "btn btn-default btn-sm btn-join"
    -else
      = form_for current_user.memberships.build(:group_id => group.id), :html => {:id => "group_#{group.id}"} , remote: true  do |f|                                          
        = f.hidden_field :group_id
        = f.submit "Join", class: "btn btn-default btn-sm btn-join"
      / =form_for group do |f|
      /   =hidden_field_tag('group[member_ids][]', current_user.id)
      /   =f.submit "Join", :class => "btn btn-mini"
-else
  /=link_to_modal "Join", new_user_path(:group_id => group.id), :class => "btn btn-mini", :remote => true
  -if group.private?
    / =form_tag(private_groups_path,  method: :put) do
    /   =hidden_field_tag :group_id, group.id
    /   =hidden_field_tag('group[member_ids][]', current_user.id)
    /   %div.span3
    /     =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
    /   =submit_tag "Join", :class => "btn btn-mini"
    / =link_to_modal "Join", new_user_path(:group_id => group.id), :class => "btn btn-mini", :remote => true
    =link_to "Private", groups_url(group), class: "btn btn-default btn-sm"
  -else
    = form_for @user.memberships.build(:group_id => group.id), :html => {:id => "group_#{group.id}"}  do |f|                                          
      = f.hidden_field :group_id
      = f.submit "Join", class: "btn btn-default btn-sm btn-join"

app/views/groups/edit.html.haml
%h1 Editing group
-if current_user && @group.owner == current_user || current_user.admin?
  = render 'form'

  = link_to 'Show', @group
  \|
  = link_to 'Back', groups_path
-else
  %p you are not the admin for this group
  =link_to "Go back to group page", group_path(@group)

app/views/groups/index.html.haml
.container
  %div.row
    %div.col-lg-3.group-categories
      %h3 Categories
      
      
      /////// FOR LATER IMPLEMENTATION::::
      /////// SEARCH BY ZIP CODE/REGION
      / =form_for '/groups/nearby', :url => nearby_groups_path do |f|
      /   /=f.hidden_field :zipcode, id: "zipcode", value: "93105"
      /   =f.label "Zipcode"
      /   =f.text_field :zipcode
      /   =f.submit "Search"
      
      / =form_tag(groups_path, method: :get) do
      /   .input-group
      /     =text_field_tag :zipcode, nil,:class => "form-control", :placeholder =>"Search by Zipcode", type: "text"
      /     %span.input-group-btn
      /       =button_tag "Go", name: nil, :class => "btn btn-default btn-lg", :type => "button"
             
      .page-element-background
        %ul
          -@g_categories.each do |gcat|
            %li.chevron_right
              =link_to gcat.name, group_category_path(gcat), :class => "chevron_right"
        -if current_user
          =link_to "Create a group", new_group_path, :class => "btn btn-default group-button", :role => "button", :id => "front_page_new_group"
        -else
          =link_to "Create a group", new_user_registration_path, :class => "btn btn-default group-button", :role => "button", :id => "front_page_new_group"
    %div.col-lg-9
      %div.row
        .col-xs-3
          %h3 Groups
        .col-xs-9
          = form_tag('groups', :remote => true, html: { class: "group-sort"}) do
            = select_tag :sort, options_for_select(Group.translated_searchable_columns, params[:sort]),  {:prompt => 'Sort By:', :class => "group-sort"}
            /= select_tag "name", options_from_collection_for_select(@group_attributes, "name", nil),  { :include_blank => true , :class => "group_select"}


          / %div.col-lg-9
          /   %ul.nav-tabs
          /     %li 
          /Sort by: closest, newest, oldest, most popular
          / %ul.breadcrumb
          /   %li
          /     =link_to "All", groups_path
          /   %li
          /     =link_to @group_category, group_category_path(@group_category)
      %div.row
        .page-element-background
          %div#groups_list
            .col-lg-12
              =render @groups, :as => "group_feed_item"
  / %table
  /   %tr
  /     %th Name
  /     %th Description
  /     %th Group category
  /     %th
  /     %th
  /     %th
  /     %th # of members
  / 
  /   - @groups.each do |group|
  /     %tr
  /       %td= group.name
  /       %td= group.description
  /       %td= group.group_category
  /       %td= link_to 'Show', group
  /       %td= link_to 'Edit', edit_group_path(group)
  /       %td= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }
  /       %td #{group.members.count} 
  %br

  = link_to 'New Group', new_group_path



  /Categories side bar
  /Content area
  //tab nav bar: alphabetical, newest, most popular
  //groups: image, name, description, join button


/ -if current_user && current_user.admin?
/   = form_tag bulk_update_groups_path do
/     %table
/       
/       %th Group
/       %th 1
/       %th 2
/       %th 3
/       %th 4
/       %th 5
/       %th 6
/       - @groups.each do |g|
/         %tr
/           %td =g.name
/           -@group_categories.each do |gc|
/             %td= check_box_tag "group_category_id[]", gc.id
/ 
/     = button_tag "Update Groups"

app/views/groups/index.js.erb
$("#groups_list").html('<%= j render("group_list") %>').fadeIn('slow');

app/views/groups/nearby.html.haml
%div.row
  %div.span3
    %h3 Categories
    /put region search bar here
    =form_for :nearby, :remote => true, :url => nearby_groups_path do |f|
      /=f.hidden_field :zipcode, id: "zipcode", value: "93105"
      =f.label "Zipcode"
      =f.text_field :zipcode
      =f.submit "Search"
    %ul.nav
      -@g_categories.each do |gcat|
        =link_to gcat.name, group_category_path(gcat), :class => "span2 chevron_right"
  %div.span9
    %h3 Groups
    / %div.span9
    /   %ul.nav-tabs
    /     %li 
    /Sort by: closest, newest, oldest, most popular
    / %ul.breadcrumb
    /   %li
    /     =link_to "All", groups_path
    /   %li
    /     =link_to @group_category, group_category_path(@group_category)
    %p search returned #{pluralize(@group_count, 'group')}
    =render @groups, :as => "group_feed_item"
/ %table
/   %tr
/     %th Name
/     %th Description
/     %th Group category
/     %th
/     %th
/     %th
/     %th # of members
/ 
/   - @groups.each do |group|
/     %tr
/       %td= group.name
/       %td= group.description
/       %td= group.group_category
/       %td= link_to 'Show', group
/       %td= link_to 'Edit', edit_group_path(group)
/       %td= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }
/       %td #{group.members.count} 
%br

= link_to 'New Group', new_group_path



/Categories side bar
/Content area
//tab nav bar: alphabetical, newest, most popular
//groups: image, name, description, join button

app/views/groups/new.html.haml
.col-lg-3
%div.col-lg-6.page-element-background
	
	%h1
		New group at
		%span#new_group_school_image
			=image_tag(@school.image.url(:thumb), :alt => @school.name)
	= render 'form'

app/views/groups/show.html.haml
/ %p#notice= notice



/ IMAGE, GROUP NAME, DESCRIPTION
%div.row-fluid.group-header
  -unless @group.assets.empty?
    %div.span3
      =link_to image_tag(@group.assets.empty?  ? '/assets/small.png': @group.assets.first.image.url(:medium), :alt => @group.name), group_url(@group), :class => "thumbnail"
  %div.span9
    %h1 #{@group.name}
    -if @group.private?
      %p (private group)
    %div.row-fluid
      %p #{@group.description}
      =render "shared/group_show_join", :group => @group
    / %p
    /   %b Name:
    /   = @group.name
    / %p
    /   %b Description:
    /   = @group.description
    / %p
    /   %b Group category:
    /   = @group.group_category
    
    

/ -if @group.private? && current_user && current_user.admin?
/   =link_to "Show Members","#", :class => "show-members-link"
/   =link_to "Hide", "#", :class => "hide-link",:style => "display:none;"
/   %div.private-user-list{:style => "display:none;"}
/     -@group.members.each do |member|
/       %p #{member.name ? member.name : member.email}
/   %p Group password will be included in the invite email
/   = render :partial => 'invite', :locals => {:group => @group}
/   -unless @group.posts.empty?
/     %h2 Posts
/     =render :partial => 'shared/feed',:locals => {:feed_items => @posts}  




/ PRIVATE GROUPS
-if @group.private? && @group.members.include?(current_user)
  %div.row-fluid
    %div.span8
      =link_to "Show Members","#", :class => "show-members-link"
      =link_to "Hide", "#", :class => "hide-link",:style => "display:none;"
      %div.private-user-list{:style => "display:none;"}
        -@group.members.each do |member|
          %p #{member.name ? member.name : member.email}
      -unless @group.posts.empty?
        %h2 Posts
        =render :partial => 'shared/group_post_feed', :collection => @posts, :as => :feed_item
    %div.span4
      -if flash[:wrong_password]
        %p#wrong_password= "Wrong password homie"
      %p Group password will be included in the invite email
      = render :partial => 'invite', :locals => {:group => @group}

-else
  /POSTS and INVITE
  %div.row-fluid
    %div.span8
      -if !@posts.empty?
        %h2 Posts:
        =render :partial => 'shared/group_post_feed', :collection => @posts, :as => :feed_item
      -else
        %h2 Posts:
        =link_to "None! Click here to post something", new_post_path
    %div.span4
      /=render "shared/simple_join", :group => @group  
      -if current_user && !@group.private?
        = render :partial => 'invite', :locals => {:group => @group}
      %h3 More Groups:
      =render :partial => 'feed/random_group_feed', :locals => {:feed_items => @random_groups}
  /=render "join_form", :group => @group







-if current_user && current_user.groups_as_owner.include?(@group)
  = link_to 'Edit', edit_group_path(@group)
  |
  = link_to 'Destroy!', @group, method: :delete, data: { confirm: 'Are you sure?' }



-if current_user && current_user.admin?
  = form_tag bulk_update_path do
    =hidden_field_tag :group_id, @group.id
    %table
      %th Delete
      %th Name
      - @group.memberships.each do |membership|
        %tr
          %td= check_box_tag "delete[]", membership.id
          %td= User.find(membership.member_id).name

    = button_tag "Remove members"

app/views/groups/update.js.haml
-if @group.members.include?(current_user)
  /=render :partial => "leave"
  =link_to "Leave this group", membership_url(current_user.memberships.find_by_group_id(@group)), :method => :delete, :confirm => "Are you sure?"
-else
  / =render :partial => "join"
  =form_for @group do |f|
    =hidden_field_tag('group[member_ids][]', current_user.id)
    .action=f.submit "Join Group"