config/routes.rb
Communitymarket::Application.routes.draw do
  resources :schools

  resources :dresses

  resources :messages

  match "/404", to: "exceptions#not_found", via: [:get, :post]
 
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  get '/auth/stripe_connect/callback', to: 'stripe_connect#create'

  resources :email_settings
  resources :followships
  
  
  

  
  resources :transactions do
    collection do
      post :customer_purchase
    end
  end
  resources :memberships do
    collection do
      put :update_individual
      post :join
    end
  end
  resources :followships do
    collection do
      post :follow
    end
  end
  resources :tags

  resources :users do
    collection do
      get :new_modal
    end
    resources :posts
    resources :groups
  end
  resources :pages do
    collection do
      get :dorm_furniture
      get :school_select
    end
  end
  
  
  resources :images
  resources :group_categories
  resources :post_categories
  resources :groups do
    collection do
      put :bulk_update
      put :private
    end
  end

  resources :posts do
    collection do
      get :sort_name
    end
    member do
      get :deactivate
      get :reactivate
      get :complete
      get :undo_completed
    end
    resources :assignments
  end
  
  match '/textbooks', to: "pages#textbooks"
  match '/admin', to: "pages#admin"
  match '/feed', :to =>"pages#feed"
  match '/bulk_update', :to => "groups#bulk_update"
  match '/for_sale', :to => "pages#for_sale"
  match '/borrow_rent', :to => "pages#borrow_rent"
  match '/services', to: "pages#services"
  match '/wanted', :to => "pages#wanted"
  match '/transactions/customer_purchase', :to => "transactions#customer_purchase"
  match '/memberships/join', :to => "memberships#join"
  match '/followships/follow', :to => "followships#join"
  match '/followships/leave', :to => "followships#leave", :via => :delete
  match '/groups/nearby', :to => "groups#nearby"
  match '/search', :to => 'search#index'
  match '/search_tags', :to => 'tags#search'
  match '/about', :to => 'pages#about'
  match '/jobs', to: 'pages#jobs'
  match '/landing', :to => 'pages#landing'
  match '/marketplace', to: 'pages#marketplace'
  match '/invites', :to => 'invites#new', via: :post
  match '/contacts', :to => 'contacts#new', via: :post

  mount CommunityMarket::API =>'/'
  get "/docs" => 'docs#index'

  root :to => 'pages#index'
  
  

end

app/views/shared/_banner_group.html.erb
<% unless groups.nil? %>
  <h4>Join some groups to notify members when you post</h4>

  <% groups.take(6).each do |group| %>

      <div class="row group" id="group_<%= group.id %>">
        <div class="banner-group-image">
          <%= link_to image_tag(group.assets.empty?  ? '/assets/small.png': group.assets.first.image.url(:small), :alt => group.name), group_url(group) %>
        </div>
        <div>
          <%= link_to group.name, group_url(group) %>
        </div>
        <div>
          <% if group.private? %>
            <% if !current_user %>
            <% else %>
              <% unless current_user && current_user.groups_as_member.include?(group) %>
                <%= link_to "Join", group_url(group), class: "btn btn-mini"%>
              <% end %>
            <% end %>
          <% else %>
            <% unless current_user && current_user.groups_as_member.include?(group) %>
              <%= render "groups/join_form", :group => group %>
            <% end %>
          <% end %>
        </div>

      </div>

  <% end %>
<% end %>

app/views/shared/_banner_group.html.haml
-unless groups.nil?
  -groups.take(6).each do |group|
    %div.col-lg-2.banner-group-body
      %div{:id=>"group_#{group.id}"}
      %div.row.banner-group-image
        =link_to image_tag(group.assets.empty?  ? '/assets/small.png': group.assets.first.image.url(:small), :alt => group.name), group_url(group)
      %div.row
        =link_to group.name, group_url(group)
      %div.row.banner-group-footer
        -if group.private?
          -if !current_user
    
            /= render "groups/join_form", :group => group
          -else
            -unless current_user && current_user.groups_as_member.include?(group)
              =link_to "Join", group_url(group), class: "btn btn-mini"
        -else
          -unless current_user && current_user.groups_as_member.include?(group)
            = render "groups/join_form", :group => group

app/views/shared/_banner_group_haml.html.haml
-unless groups.nil?
  -groups.take(6).each do |group|
    %div.col-lg-2.banner-group-body
      %div{:id=>"group_#{group.id}"}
      %div.row.banner-group-image
        =link_to image_tag(group.assets.empty?  ? '/assets/small.png': group.assets.first.image.url(:small), :alt => group.name), group_url(group)
      %div.row
        =link_to group.name, group_url(group)
      %div.row.banner-group-footer
        -if group.private?
          -if !current_user
    
            /= render "groups/join_form", :group => group
          -else
            -unless current_user && current_user.groups_as_member.include?(group)
              =link_to "Join", group_url(group), class: "btn btn-mini"
        -else
          -unless current_user && current_user.groups_as_member.include?(group)
            = render "groups/join_form", :group => group

app/views/shared/_group_feed.html.haml
-if feed_items
  -if feed_items.first.is_a?(Post)
    =render :partial => 'shared/post_feed', :collection => feed_items, :as => :feed_item
  -else
    =render :partial => 'shared/group_feed_item', :collection => feed_items, :as => :feed_item

  / =will_paginate feed_items
  /=will_paginate @page_results
  =paginate @posts
-else
  %p no array

app/views/shared/_group_feed_item.html.haml
%div.row-fluid
  %div.span10
    %div.row-fluid
      %span.feed-title
        = link_to feed_item.name, group_url(feed_item)
  %div.span2
    = render "groups/join_form", :group => feed_item

app/views/shared/_group_show_join.html.haml
%div{:id => "join_button_"+group.id.to_s}
  -if current_user
    -if group.members.include?(current_user)
      /=render :partial => "leave"
      = form_for current_user.memberships.find_by_group_id(group), html: { :method => :delete, :class => "form" }, remote: true do |f|
        =f.hidden_field :group_id, :value => group.id                                            
        = f.submit "Leave", class: "anti-button"
      /=link_to "Leave", membership_url(current_user.memberships.find_by_group_id(group)), :method => :delete, :confirm => "Are you sure?"
    -else

      -if group.private?
        =form_tag(private_groups_path,  method: :put) do
          =hidden_field_tag :group_id, group.id
          =hidden_field_tag('group[member_ids][]', current_user.id)
          %div.span3
            =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
          =submit_tag "Join this group", :class => "btn btn-default"
      -else
        = form_for current_user.memberships.build(:group_id => group.id), :url => join_memberships_path, remote: true  do |f|                                          
          = f.hidden_field :group_id
          = f.submit "Join this group", class: "btn btn-default"
        / =form_for group do |f|
        /   =hidden_field_tag('group[member_ids][]', current_user.id)
        /   =f.submit "Join", :class => "btn btn-mini"
  -else
    -if group.private?
      / =form_tag(private_groups_path,  method: :put) do
      /   =hidden_field_tag :group_id, group.id
      /   =hidden_field_tag('group[member_ids][]', current_user.id)
      /   %div.span3
      /     =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
      /   =submit_tag "Join", :class => "btn btn-mini"
      /=link_to_modal "Join", new_user_path(:group_id => group.id), :class => "btn btn-mini", :remote => true 
    -else
      = form_for @user.memberships.build(:group_id => group.id), :url => join_memberships_path  do |f|                                          
        = f.hidden_field :group_id
        = f.submit "Join this group", class: "btn btn-default"

app/views/shared/_post_feed.html.haml
-if feed_item.premium?
  =render 'shared/post_feed_item_premium', :feed_item => feed_item
-else
  =render 'shared/post_feed_item_slim', :feed_item => feed_item

app/views/shared/_post_feed_item_premium.html.haml
/ /THIS IS THE MODULAR POST THAT IS LISTED/SHOWN in FEEDS
/ /OK?
/ /GOOD.
/ %div.feed-item.row-fluid
/   %div.image.span2
/     =link_to image_tag(feed_item.assets.empty?  ? '/assets/small.png': feed_item.assets.first.image.url(:small), :alt => feed_item.title), post_url(feed_item)
/   %div.span8
/     %div.row-fluid
/       /price
/       /make price a variable that can be passed into the modal partials below so
/       /that on credit card charge, we know how much to charge
/       %span.feed-title
/         .feed-title= link_to feed_item.title, post_url(feed_item)
/     %div.row-fluid.description-row
/       %span.description
/         = truncate(feed_item.description, 25)
/     %div.row-fluid.tag-row
/       -feed_item.tags.each do |tag|
/         =link_to tag.name, tag_url(tag), :class => "tag"
/       %span.slim-feed-timestamp #{time_ago_in_words(feed_item.created_at)} ago.
/   %div.span2
/     / -if feed_item.price?
/     /   /email button
/     /   %a.btn{ :href => "mailto:#{feed_item.email}", :role => "button"}$ #{feed_item.price} | Email
/     / -else
/   
/     /BUY button:
/     / %a.btn.buy-button.btn-mini{ "data-target" => "#buy_modal", "data-toggle" => "modal", 'data-remote' => "/transactions/new", :href => "/transactions/new", :role => "button"} Buy
/     %a.btn.btn-mini{ :href => "mailto:#{feed_item.email}", :role => "button"} Email
/     -if feed_item.tier_id
/       -if signed_in? && current_user.stripe_customer_id.nil? == false
/         /IF: signed_in and no c#, THEN: user_credit_modal
/         =render 'user_you_sure_modal'
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id 
/       -elsif signed_in? && current_user.stripe_customer_id.nil?
/         /IF: signed_in and yes c# THEN: user_you_sure_modal
/      
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id 
/       
/         %div#transaction_modal.modal.hide
/         /=render 'user_credit_modal'
/         /set width fo this somehow
/ 
/       -else
/         /IF: not signed_in THEN: non_user_credit_modal
/         / %div#transaction_modal.modal.hide
/         /   = render "transactions/new_modal"
/         / %a.btn.btn-mini{"data-target" => "#transaction_modal", "data-toggle" => "modal"}
/       
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id    
/         /%a.btn.btn-mini{ :href => "mailto:#{feed_item.email}", :role => "button"} Email
/         /%div#buy_modal.modal.fade{ 'data-postid' => "#{feed_item.id}", :role => "dialog",:style=>"display:none"}
/         /=render :partial => 'transactions/form'
/         /NONAJAX THAT WORKS:
/         /=link_to "Buy", new_transaction_path(:post_id => feed_item.id)
/     
/ 
/ 
/ 
/ / -if signed_in? && current_user.stripe_customer_id.nil? == false
/ /   %div.buy_modal.modal{:role => "dialog",:style=>"display:none"}
/ /     =render 'user_you_sure_modal'
/ / -elsif signed_in? && current_user.stripe_customer_id.nil?
/ /   =render 'user_credit_modal'
/ / -else
/ /   =render 'non_user_credit_modal'
/ 
/ 
/ 
/ 
/ 
/ 
/ / - if current_user?(feed_item.user)
/ /   = link_to "delete", feed_item, method:  :delete, confirm: "You sure?",title:   feed_item.content
/THIS IS THE MODULAR POST THAT IS LISTED/SHOWN in FEEDS
/OK?
/GOOD.

%div.image.span2
  =link_to image_tag(feed_item.assets.empty?  ? '/assets/small.png': feed_item.assets.first.image.url(:small), :alt => feed_item.title), post_url(feed_item)
%div.span8
  %div.row-fluid
    /price
    /make price a variable that can be passed into the modal partials below so
    /that on credit card charge, we know how much to charge
    %span.feed-title
      .feed-title= link_to feed_item.title, post_url(feed_item)
  %div.row-fluid.description-row
    %span.description
      = truncate(feed_item.description, 25)
%div.span2
%a.btn.btn-mini{ :href => "mailto:#{feed_item.email}", :role => "button"} Email
/ %i.icon-large.icon-envelope
-if feed_item.tier_id
  -if signed_in? && current_user.stripe_customer_id
    /IF: signed_in and no c#, THEN: user_credit_modal
    /=render 'user_you_sure_modal'
    / =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
    = form_for @transaction, :url => customer_purchase_transactions_path(@transaction), :html => {:id => "slim_post_customer_buy_button"}  do |f|
      - if @transaction.errors.any?
        .error_messages
          %h2
            = pluralize(@transaction.errors.count, "error")
            prohibited this transaction from being saved:
          %ul
            - @transaction.errors.full_messages.each do |msg|
              %li= msg                                          
      =f.hidden_field :post_id, :value => feed_item.id
      =f.submit "Buy", class: "btn btn-mini btn-success"
  -elsif signed_in? && current_user.stripe_customer_id.nil?
    /IF: signed_in and yes c# THEN: user_you_sure_modal
 
    / =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id 
    =link_to 'Buy', new_transaction_path(:post_id => feed_item.id), :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id 
    %div#transaction_modal.modal.hide

  -else
    /=link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
    =link_to 'Buy', new_transaction_path(:post_id => feed_item.id), :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
-elsif feed_item.price
  %span.non-tier-price$#{feed_item.price}


/ -if signed_in? && current_user.stripe_customer_id.nil? == false
/   %div.buy_modal.modal{:role => "dialog",:style=>"display:none"}
/     =render 'user_you_sure_modal'
/ -elsif signed_in? && current_user.stripe_customer_id.nil?
/   =render 'user_credit_modal'
/ -else
/   =render 'non_user_credit_modal'

%div.row-fluid.tag-row
-feed_item.tags.each do |tag|
  =link_to tag.name, tag_url(tag), :class => "tag"
%span.slim-feed-timestamp #{time_ago_in_words(feed_item.created_at)} ago.




/ - if current_user?(feed_item.user)
/   = link_to "delete", feed_item, method:  :delete, confirm: "You sure?",title:   feed_item.content

app/views/shared/_post_feed_item_slim.html.haml
/ /THIS IS THE MODULAR POST THAT IS LISTED/SHOWN in FEEDS
/ /OK?
/ /GOOD.
/ 
/ %div.slim-feed-item.row-fluid
/ 
/   %div.span10
/     %div.row-fluid.slim-feed-title-row
/       /price
/       /make price a variable that can be passed into the modal partials below so
/       /that on credit card charge, we know how much to charge      
/       %span.slim-feed-title
/         = link_to feed_item.title, post_url(feed_item), :class => "slim-feed-title"
/       -unless feed_item.assets.first.nil?
/         %i.icon-medium.icon-camera
/       -feed_item.tags.each do |tag|
/         =link_to tag.name, tag_url(tag), :class => "tag"
/       %span.slim-feed-timestamp #{time_ago_in_words(feed_item.created_at)} ago.
/ 
/       
/ 
/   %div.span2
/     %a.btn.btn-mini{ :href => "mailto:#{feed_item.email}", :role => "button"} Email
/     -if feed_item.tier_id
/       -if signed_in? && current_user.stripe_customer_id.nil? == false
/         /IF: signed_in and no c#, THEN: user_credit_modal
/         =render 'user_you_sure_modal'
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id 
/       -elsif signed_in? && current_user.stripe_customer_id.nil?
/         /IF: signed_in and yes c# THEN: user_you_sure_modal
/      
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id 
/       
/         %div#transaction_modal.modal.hide
/ 
/       -else
/         =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini", :data_postid => feed_item.id    
/ 
/ 
/ 
/ 
/THIS IS THE MODULAR POST THAT IS LISTED/SHOWN in FEEDS
/OK?
/GOOD.


%div.span9
  %div.row-fluid.slim-feed-title-row
    /price
    /make price a variable that can be passed into the modal partials below so
    /that on credit card charge, we know how much to charge      
    %span.slim-feed-title
      = link_to feed_item.title, post_url(feed_item), :class => "slim-feed-title"
    -unless feed_item.assets.first.nil?
      %i.icon-medium.icon-camera
    /%span.slim-feed-timestamp #{time_ago_in_words(feed_item.created_at)} ago.
  / %div.row-fluid
  /   -feed_item.tags.each do |tag|
  /     =link_to tag.name, tag_url(tag), :class => "tag"




%div.span3
  -if feed_item.tier_id
    -if signed_in? && current_user.stripe_customer_id.nil? == false
      /IF: signed_in and no c#, THEN: user_credit_modal
      /=render 'user_you_sure_modal'
      / =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
      =link_to 'Buy | $#{Tier.find(feed_item.tier_id).price/100}', new_transaction_path(:post_id => feed_item.id), :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id 
    -elsif signed_in? && current_user.stripe_customer_id.nil?
      /IF: signed_in and yes c# THEN: user_you_sure_modal

      / =link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id 
      =link_to 'Buy | $#{Tier.find(feed_item.tier_id).price/100}', new_transaction_path(:post_id => feed_item.id), :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id 
      %div#transaction_modal.modal.hide

    -else
      /=link_to_modal 'Buy', new_transaction_path(:post_id => feed_item.id), :remote => true, :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
      =link_to 'Buy | $#{Tier.find(feed_item.tier_id).price/100}', new_transaction_path(:post_id => feed_item.id), :id => "new_transaction_link", :class => "btn btn-mini btn-success", :data_postid => feed_item.id
  -elsif feed_item.price
    %span.non-tier-price $#{feed_item.price} [Cash OBO]
  %a.btn.btn-mini{ :href => "mailto:#{feed_item.email}", :role => "button"} Email

app/views/shared/_post_search_bar.html.haml
/ .container
/   .search-row
/     .col-lg-3
/       =link_to "Post Something", new_post_path,  class: "btn btn-default btn-primary pull-left", :role => "button"
/     .col-lg-2
/       .btn-group
/         %button#shop_by_category_button.btn.btn-large.btn-default.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
/           Shop By Category
/           %span.caret
/         %ul.dropdown-menu{role: "menu"}
/           -@browse_by_array.each do |category|
/             -if category.is_a?(Tag)
/               %li
/                 %a{href: category ? tag_url(category) : "#"} #{category.name.titleize}
/             -elsif category.is_a?(PostCategory)
/               %li
/                 %a{href: category ? post_category_url(category) : "#"} #{category.name.titleize}
/     .col-lg-7
/       =search_form_for @q, :url => { :controller => "search", :action => "index"}, :html => { :class => "form-inline"} do |f|
/         .input-group.input-group-lg
/           =f.text_field :name_cont, :class => "form-control", :placeholder => "search for stuff or groups...type it here"
/           %span.input-group-btn
/             =f.submit 'Search', :class => "btn btn-flat", :id => "btn_search"
/
.container
  %div.search-row

    / Removed "Post Something" link here as it was redundant. Already "New Post" in top nav bar.

    %div.col-md-8
      =render :partial => "search/search_form"

    %div.col-md-4
      =render :partial => "search/category_dropdown"

app/views/shared/_sign_up.html.haml
#school_image
= simple_form_for @user,  html: {role:"form", class: 'form'} do |f|
  -if params[:group_id]
    =hidden_field_tag('group[member_ids][]', @user.id)
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg


  %div#school.form-group
    //image of school
    //collection select of all schools
    = f.collection_select(:school_id, School.all, :id, :name, {:prompt => 'Choose your school:'},:class => "form-control", id: "school_select", "data-remote" => true, "data-url" => school_select_pages_path)

  %div#name_field.form-group
    / =f.label :name, :class => 'control-label'
    / %div.controls
    =f.text_field :name, type:"text",:class => "form-control", :placeholder => "Eleazar Wheelock"        
  %div.form-group
    / =f.label :email, :class => 'control-label'
    /%div.controls
    =f.text_field :email,type:"email", :class => "form-control", :placeholder => "elly@dartmouth.edu"  
  %div.form-group
    /=f.label :password, :class => 'control-label'
    /%div.controls
    =f.password_field :password, type:"password",:class => "form-control", :placeholder => "Password"  
  =f.submit "Sign Up", class: "btn btn-default btn-primary", id: "cta-peek-2"

app/views/shared/_simple_follow.html.haml
/ %div{:id => "follow_button_"+tag.id.to_s}

-if current_user
  -if tag.followers.include?(current_user)
    = form_for current_user.followships.find_by_followed_id(tag), html: {:method => :delete, :class => "form" }, remote: true do |f|
      =f.hidden_field :followed_id, :value => tag.id                                            
      = f.submit "unfollow", class: "anti-button", style: "margin-left: 10px; margin-right: 15px;"
  -else
    = form_for current_user.followships.build(:followed_id => tag.id), :url => follow_followships_path, remote: true  do |f|                                          
      = f.hidden_field :followed_id
      = f.submit "follow", class: "btn btn-default btn-mini"

-else
  = form_for @user.followships.build(:followed_id => tag.id), :url => follow_followships_path  do |f|                                          
    = f.hidden_field :followed_id
    = f.submit "follow", class: "btn btn-default btn-mini"

app/views/shared/_simple_join.html.haml
%div{:id => "join_button_"+group.id.to_s}
  -if current_user
    -if group.members.include?(current_user)
      /=render :partial => "leave"
      = form_for current_user.memberships.find_by_group_id(group), html: { :method => :delete, :class => "form" }, remote: true do |f|
        =f.hidden_field :group_id, :value => group.id                                            
        = f.submit "Leave", class: "anti-button"
      /=link_to "Leave", membership_url(current_user.memberships.find_by_group_id(group)), :method => :delete, :confirm => "Are you sure?"
    -else

      -if group.private?
        =form_tag(private_groups_path,  method: :put) do
          =hidden_field_tag :group_id, group.id
          =hidden_field_tag('group[member_ids][]', current_user.id)
          %div.span3
            =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
          =submit_tag "Join", :class => "btn btn-default btn-mini btn-join"
      -else
        = form_for current_user.memberships.build(:group_id => group.id), :url => join_memberships_path, remote: true  do |f|                                          
          = f.hidden_field :group_id
          = f.submit "Join", class: "btn btn-default btn-mini btn-join"
        / =form_for group do |f|
        /   =hidden_field_tag('group[member_ids][]', current_user.id)
        /   =f.submit "Join", :class => "btn btn-mini"
  -else
    -if group.private?
      / =form_tag(private_groups_path,  method: :put) do
      /   =hidden_field_tag :group_id, group.id
      /   =hidden_field_tag('group[member_ids][]', @user.id)
      /   %div.span3
      /     =text_field_tag :password, nil, :class => "input-block-level inline", :placeholder => "Password", :id => "join_private_group"
      /   =submit_tag "Join", :class => "btn btn-mini"
      =link_to_modal "Join", new_user_path(:group_id => group.id), :class => "btn btn-default btn-mini", :remote => true 
    -else
      = form_for @user.memberships.build(:group_id => group.id), :url => join_memberships_path  do |f|                                          
        = f.hidden_field :group_id
        = f.submit "Join", class: "btn btn-default btn-mini btn-join"

app/views/shared/_your_group_feed.html.haml
%div.row-fluid
  / %div.image.span3
  /   =link_to image_tag(feed_item.assets.empty?  ? '/assets/small.png': feed_item.assets.first.image.url(:small), :alt => feed_item.name), group_url(feed_item)
  %div.span10
    %div.row-fluid
      %span.feed-title
        = link_to group.name, group_url(group)