config/routes.rb
Communitymarket::Application.routes.draw do
  resources :schools

  resources :dresses

  resources :messages

  match "/404", to: "exceptions#not_found", via: [:get, :post]
 
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  get '/auth/stripe_connect/callback', to: 'stripe_connect#create'

  resources :email_settings
  resources :followships
  
  
  

  
  resources :transactions do
    collection do
      post :customer_purchase
    end
  end
  resources :memberships do
    collection do
      put :update_individual
      post :join
    end
  end
  resources :followships do
    collection do
      post :follow
    end
  end
  resources :tags

  resources :users do
    collection do
      get :new_modal
    end
    resources :posts
    resources :groups
  end
  resources :pages do
    collection do
      get :dorm_furniture
      get :school_select
    end
  end
  
  
  resources :images
  resources :group_categories
  resources :post_categories
  resources :groups do
    collection do
      put :bulk_update
      put :private
    end
  end

  resources :posts do
    collection do
      get :sort_name
    end
    member do
      get :deactivate
      get :reactivate
      get :complete
      get :undo_completed
    end
    resources :assignments
  end
  
  match '/textbooks', to: "pages#textbooks"
  match '/admin', to: "pages#admin"
  match '/feed', :to =>"pages#feed"
  match '/bulk_update', :to => "groups#bulk_update"
  match '/for_sale', :to => "pages#for_sale"
  match '/borrow_rent', :to => "pages#borrow_rent"
  match '/services', to: "pages#services"
  match '/wanted', :to => "pages#wanted"
  match '/transactions/customer_purchase', :to => "transactions#customer_purchase"
  match '/memberships/join', :to => "memberships#join"
  match '/followships/follow', :to => "followships#join"
  match '/followships/leave', :to => "followships#leave", :via => :delete
  match '/groups/nearby', :to => "groups#nearby"
  match '/search', :to => 'search#index'
  match '/search_tags', :to => 'tags#search'
  match '/about', :to => 'pages#about'
  match '/jobs', to: 'pages#jobs'
  match '/landing', :to => 'pages#landing'
  match '/marketplace', to: 'pages#marketplace'
  match '/invites', :to => 'invites#new', via: :post
  match '/contacts', :to => 'contacts#new', via: :post

  mount CommunityMarket::API =>'/'
  get "/docs" => 'docs#index'

  root :to => 'pages#index'
  
  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :description, :follower_ids
  has_many :taggings
  has_many :posts, :through=> :taggings
  has_many :followships, :foreign_key => :followed_id
  has_many :followers, through: :followships, source: :follower, :foreign_key => :follower_id
  
  
  def self.tokens(query)
    tags = where("name like ?","%#{query}%")
    if tags.empty?
      [{:id=> "<<<#{query}>>>", :name=> "New: \"#{query}\"", :description=>""}]
    else
      tags
    end
  end
  
  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(:name => $1).id }
    tokens.split(',')
  end

  def has_this_user user
    self.followers.include? user
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order(:name)
    @popular_tags = get_popular_tags
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags.tokens(params[:t]) }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @transaction = Transaction.new
    @tag = Tag.find(params[:id])
    unless @tag.posts.empty?
		  @posts = @tag.posts.select{|x| x.active?}.sort { |x,y| y.created_at <=> x.created_at }
		  @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(50)
		end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
  def search
    @q = Tag.search(params[:q])
    @tags = @q.result
    @tags_count = @tags.count
  end
  
  
  private
  def get_popular_tags
    adapter_type = ActiveRecord::Base.connection.adapter_name.downcase.to_sym
    case adapter_type
    when :mysql
      # do the MySQL part
    when :sqlite
      # do the SQLite3 part
      Tag.joins(:taggings).select('tags.*, count(tag_id) as "tag_count"').group(:tag_id).order(' tag_count desc')
    when :postgresql
      Tag.joins(:taggings).select('tags.*, count(tag_id) as "tag_count"').group('tags.id').order(' tag_count desc')

    else
      raise NotImplementedError, "Unknown adapter type '#{adapter_type}'"
    end
    
  end
      
      
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_follow_form.html.haml
-if current_user
  -if tag.followers.include?(current_user)
    /=render :partial => "leave"
    / =link_to "Unfollow", (current_user.followships.find_by_followed_id(tag)), :method => :delete, :confirm => "Are you sure?"
    
    = form_for current_user.followships.find_by_followed_id(tag), html: { :method => :delete }, remote: true do |f|
      =f.hidden_field :followed_id, :value => tag.id                                            
      = f.submit "Unfollow", class: "btn btn-large"
    
    
  -else
    / =render :partial => "join"
    
    = form_for current_user.followships.build(:followed_id => tag.id), remote: true  do |f|                                          
      = f.hidden_field :followed_id
      = f.submit "Follow", class: "btn btn-large btn-primary"
    
    / =form_for tag do |f|
    /   =hidden_field_tag('tag[follower_ids][]', current_user.id)
    /   .action=f.submit "Follow"
-else
  = form_for @user.followships.build(:followed_id => tag.id)  do |f|                                          
    = f.hidden_field :followed_id
    = f.submit "Follow", class: "btn btn-large btn-primary"
  /=link_to "Follow", new_user_path, :class => "btn btn-mini"

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/tags/_popular_tags.html.haml
-tags.each do |tag|
  %div#whole_tag
    %span#span-tag
    =link_to tag.name, tag_url(tag), :class => "tag"
%div.row-fluid
  %i.icon-large.icon-tags
  =link_to "More tags...", tags_path
  
  
  

app/views/tags/_tag.html.haml
%div.row-fluid
  %span
    %div.pull-left{:id => "follow_button_"+tag.id.to_s}
      =render 'shared/simple_follow', :tag => tag
    %div#whole_tag
      %span#span-tag
      =link_to tag.name, tag_url(tag), :class => "tag"
    / #{pluralize(tag.posts.count, 'post')}

%br/
    

app/views/tags/_your_tags.html.haml
-tags.each do |tag|
  %div#whole_tag
    %span#span-tag
    =link_to tag.name, tag_url(tag), :class => "tag"
%div.row-fluid
  %i.icon-large.icon-tags
  =link_to "More tags...", tags_path

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%div.row
  %div.col-lg-3
    %h3 Search
    .page-element-background
      =search_form_for @q, :url => { :controller => "tags", :action => "search"}, :html => { :class => "form-inline"} do |f|
        .input-group
          =f.text_field :name_cont, type: "text", :class => "form-control col-lg-8", :placeholder => "search for tags"
          %span.input-group-btn
            = button_tag(type: 'submit', class: "btn btn-default btn-lg") do
              %span.glyphicon.glyphicon-search
      /put tag search bar here
      / =form_tag(groups_path, method: :get) do
      /   .input-group
      /     =text_field_tag :zipcode, nil,:class => "form-control", :placeholder =>"Zipcode"
      /     %span.input-group-btn
      /       =button_tag "Go", name: nil, :class => "btn-default btn", :type => "button"
      
      = link_to 'New Tag', new_tag_path, class: "btn btn-default"
    /TAG CATEGORIES?
    / %ul.nav
    /   -@g_categories.each do |gcat|
    /     =link_to gcat.name, group_category_path(gcat), :class => "span2 chevron_right"
  %div.col-lg-9
    %div.row
      %div.col-lg-3
        %h3 Popular Tags
    .page-element-background    
      =render @popular_tags


/

/ %div.col-lg-6.posts-nav
/   %span
/     =link_to "For Sale", for_sale_path, id: 'for_sale_link'
/   %span 
/     =link_to "Wanted", wanted_path, id: 'wanted_link'
/   %span
/     =link_to "For Rent/Borrow", borrow_rent_path, id: "borrow_rent_link"
/=link_to "Create a group", new_group_path, :class => "btn group-button pull-right", :role => "button", :id => "front_page_new_group"
/ %div.col-lg-9
/   %ul.nav-tabs
/     %li 
/Sort by: closest, newest, oldest, most popular
/ %ul.breadcrumb
/   %li
/     =link_to "All", groups_path
/   %li
/     =link_to @group_category, group_category_path(@group_category)

/Categories side bar
/Content area
//tab nav bar: alphabetical, newest, most popular
//groups: image, name, description, join button

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/search.html.haml
%div.row
  %div.col-lg-3
    %h3 Search
    =search_form_for @q, :url => { :controller => "tags", :action => "search"}, :html => { :class => "form-inline"} do |f|
      .input-group
        =f.text_field :name_cont, type: "text", :class => "form-control col-lg-8", :placeholder => "search for tags"
        %span.input-group-btn
          = button_tag(type: 'submit', class: "btn btn-default btn-lg") do
            %span.glyphicon.glyphicon-search
    /put tag search bar here
    / =form_tag(groups_path, method: :get) do
    /   .input-group
    /     =text_field_tag :zipcode, nil,:class => "form-control", :placeholder =>"Zipcode"
    /     %span.input-group-btn
    /       =button_tag "Go", name: nil, :class => "btn-default btn", :type => "button"
    
    = link_to 'New Tag', new_tag_path, class: "btn btn-default"
    /TAG CATEGORIES?
    / %ul.nav
    /   -@g_categories.each do |gcat|
    /     =link_to gcat.name, group_category_path(gcat), :class => "span2 chevron_right"
  %div.col-lg-9
    %div.row
      %div.col-lg-3
        %h3 Results
    =render @tags


/

/ %div.col-lg-6.posts-nav
/   %span
/     =link_to "For Sale", for_sale_path, id: 'for_sale_link'
/   %span 
/     =link_to "Wanted", wanted_path, id: 'wanted_link'
/   %span
/     =link_to "For Rent/Borrow", borrow_rent_path, id: "borrow_rent_link"
/=link_to "Create a group", new_group_path, :class => "btn group-button pull-right", :role => "button", :id => "front_page_new_group"
/ %div.col-lg-9
/   %ul.nav-tabs
/     %li 
/Sort by: closest, newest, oldest, most popular
/ %ul.breadcrumb
/   %li
/     =link_to "All", groups_path
/   %li
/     =link_to @group_category, group_category_path(@group_category)

/Categories side bar
/Content area
//tab nav bar: alphabetical, newest, most popular
//groups: image, name, description, join button

app/views/tags/show.html.haml
%p#notice= notice

.row
  .col-lg-2
  .col-lg-8

    .page-element-background
      %h3
        #{@tag.name}
        %span{style:"display:inline-block"}
          %div{:id => "follow_button_"+@tag.id.to_s}
          =render 'shared/simple_follow', :tag => @tag
      / .row
      /   .col-lg-6
      /     %p Follow a tag so that you don't have to keep checking the marketplace to learn about new posts
    %br/
    / %p
    /   %b Description:
    /   = @tag.description
    -unless @tag.posts.empty?
      /=will_paginate @posts
      /=render @posts

      /=render :partial => 'shared/post_feed', :collection => @posts, :as => :feed_item
      .page-element-background
        =render :partial => 'feed/feed',:locals => {:feed_items => @posts}
      /=will_paginate @posts