config/routes.rb
Communitymarket::Application.routes.draw do
  resources :schools

  resources :dresses

  resources :messages

  match "/404", to: "exceptions#not_found", via: [:get, :post]
 
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  get '/auth/stripe_connect/callback', to: 'stripe_connect#create'

  resources :email_settings
  resources :followships
  
  
  

  
  resources :transactions do
    collection do
      post :customer_purchase
    end
  end
  resources :memberships do
    collection do
      put :update_individual
      post :join
    end
  end
  resources :followships do
    collection do
      post :follow
    end
  end
  resources :tags

  resources :users do
    collection do
      get :new_modal
    end
    resources :posts
    resources :groups
  end
  resources :pages do
    collection do
      get :dorm_furniture
      get :school_select
    end
  end
  
  
  resources :images
  resources :group_categories
  resources :post_categories
  resources :groups do
    collection do
      put :bulk_update
      put :private
    end
  end

  resources :posts do
    collection do
      get :sort_name
    end
    member do
      get :deactivate
      get :reactivate
      get :complete
      get :undo_completed
    end
    resources :assignments
  end
  
  match '/textbooks', to: "pages#textbooks"
  match '/admin', to: "pages#admin"
  match '/feed', :to =>"pages#feed"
  match '/bulk_update', :to => "groups#bulk_update"
  match '/for_sale', :to => "pages#for_sale"
  match '/borrow_rent', :to => "pages#borrow_rent"
  match '/services', to: "pages#services"
  match '/wanted', :to => "pages#wanted"
  match '/transactions/customer_purchase', :to => "transactions#customer_purchase"
  match '/memberships/join', :to => "memberships#join"
  match '/followships/follow', :to => "followships#join"
  match '/followships/leave', :to => "followships#leave", :via => :delete
  match '/groups/nearby', :to => "groups#nearby"
  match '/search', :to => 'search#index'
  match '/search_tags', :to => 'tags#search'
  match '/about', :to => 'pages#about'
  match '/jobs', to: 'pages#jobs'
  match '/landing', :to => 'pages#landing'
  match '/marketplace', to: 'pages#marketplace'
  match '/invites', :to => 'invites#new', via: :post
  match '/contacts', :to => 'contacts#new', via: :post

  mount CommunityMarket::API =>'/'
  get "/docs" => 'docs#index'

  root :to => 'pages#index'
  
  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  before_filter :require_admin_login, :only => [:index]
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @user = User.new
    flash[:the_post_id] = params[:post_id]
    if params[:post_id]
      @post = Post.find(params[:post_id])
      if @post.tier_id?
        @tier = Tier.find(@post.tier_id)
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
      # if request.xhr?
      #    format.html { render 'new_modal'}
      #  else
      #    format.html
      #    #format.json { render :json => @transaction }
      #  end
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  
  def create
    if @post = Post.where(:id => flash[:the_post_id]).first
    #@price = @post.price
      @tier_id = @post.tier_id
      @amount = amount_to_charge_for(@tier_id)

    else
      @amount = 1000
    end
    
    #@token = flash[:token]
    #@token = params[:transaction][:stripe_card_token]
    respond_to do |format|
      
      #-------------------------------------------------------------------------------------------#
      #---- Sign Up and Pay at Same time...[working] ---------------------------------------------#
      #-------------------------------------------------------------------------------------------#
      #non-user encountered form and entered credit details AND password- signing up and paying
      if !current_user && params[:password].present?        
        @user = User.new(:email => params[:transaction][:email], :password => params[:password], :name => params[:name])
        #@user.save_as_customer(params[:transaction][:email], @token)
        # @user.save_as_customer
        @transaction = @user.transactions.new(params[:transaction].merge(:price => @amount))
        @transaction.save_customer(@user)
        # customer = Stripe::Customer.create( :description => email, :card => params[:stripe_card_token])
        # @user.stripe_customer_id = customer.id
        if @transaction.save && @user.save
          @user.charge_as_customer(@amount)
          sign_in @user
          #format.js { render }
          @post.deactivate!
          @post.complete!
          @seller = User.find(@post.user_id)
          # @post.user_id = @user.id
          @post.save!
          if @tier_id 
            SoldPostMailer.notify(@user, @post, @seller).deliver
          end
          format.html { redirect_to @user, notice: 'You have succesfully acquired some stuff.' }
          format.json { render json: @transaction, status: :created, location: @transaction }
        else
          format.html { render action: "new" }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
        
      #-------------------------------------------------------------------------------------------#
      #---- Current User and Customer... [not working]--------------------------------------------#
      #-------------------------------------------------------------------------------------------#  
      elsif current_user && current_user.stripe_customer_id
      #already gots that CC info--- just charge 'em  
        @user = current_user
        @transaction = @user.transactions.new(params[:transaction].merge(:price => @amount).merge(:email => @user.email))
        # @transaction.save_customer(@user)
        if @transaction.save
          @user.charge_as_customer(@amount)
          @post.deactivate!
           @post.complete!
          @seller=User.find(@post.user_id)
          # @post.user_id = @user.id
          @post.save!
          if @tier_id
            SoldPostMailer.notify(@user, @post, @seller).deliver
            PurchaseCompletedMailer.notify(@user,@post,@seller).deliver
          end
          format.html { redirect_to @user, notice: 'You have succesfully acquired some stuff.' }
          format.json { render json: @user, status: :created, location: @transaction }
          
        else
          format.html { render action: "new" }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      #-------------------------------------------------------------------------------------------#
      #---- Current User and Non-Customer... [working]--------------------------------------------#
      #-------------------------------------------------------------------------------------------#
      elsif current_user && !current_user.stripe_customer_id
        #current_user without credit details encountered form
        @user = current_user
        # @user.update_payment_details(@user.email, @token)
        # @user.charge_as_customer(@amount)
        @transaction = @user.transactions.new(params[:transaction].merge(:price => @amount).merge(:email => @user.email).merge(:post_id => @post.id))
        @transaction.save_customer(@user)
        if @transaction.save
          @user.charge_as_customer(@amount)
          @post.deactivate!
           @post.complete!
          @seller=User.find(@post.user_id)
          # @post.user_id = @user.id
          @post.save!
          if @tier_id
            SoldPostMailer.notify(@user, @post, @seller).deliver
            PurchaseCompletedMailer.notify(@user,@post,@seller).deliver
          end
          format.html { redirect_to @user, notice: 'You have succesfully acquired some stuff.' }
        else
          format.html { render action: "new" }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      #-------------------------------------------------------------------------------------------#
      #---- Non-User and Non-Customer... [working]------------------------------------------------#
      #-------------------------------------------------------------------------------------------#
      else
        #non-user encountered form and didn't enter password
        @transaction = Transaction.new(params[:transaction].merge(:price => @amount))
        if @transaction.save
          @post.deactivate!
           @post.complete!
          @transaction.charge(@amount, params[:transaction][:stripe_card_token], params[:transaction][:email])
          if @tier_id
            # SoldPostMailer.notify(@user, @post, user, group).deliver
          end
          format.html { redirect_to root_path, notice: 'You have succesfully acquired some stuff.' }
        else
          format.html { render action: "new" }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end      
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'You have succesfully acquired some stuff.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def customer_purchase
    
    @user = current_user
    @transaction = @user.transactions.new(:premium => @premium, :notify_premium => @notify_premium, :tier_id => @tier_id, :price => @amount, :email => @user.email)
    if @post = Post.find(params[:transaction][:post_id])
    #@price = @post.price
      @tier_id = @post.tier_id
      @amount = amount_to_charge_for(@tier_id)
    else
      @notify_premium = params[:notify_premium]
      @premium = params[:premium]
      @amount = 1000
    end
    
    
    respond_to do |format|
      if @transaction.save
        @user.charge_as_customer(@amount)
        @post.deactivate!
         @post.complete!
        @post.user_id = @user.id
        @post.save!
        if @tier_id
          @seller = User.find(@post.user_id)
          SoldPostMailer.notify(@user, @post, @seller).deliver
        end
        format.html { redirect_to @user, notice: 'You have succesfully acquired some stuff' }
        format.json { render json: @user, status: :created, location: @transaction }
      
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  
  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
  
  def amount_to_charge_for(tier_id)
    case tier_id
      when 1 then return 250
      when 2 then return 600
      when 3 then return 1200
      when 4 then return 3000
      when 5 then return 6000
      when 6 then return 11000
    end    
  end
  def require_admin_login
    unless current_user.admin?
      flash[:error] = "You must be logged in as an admin to access this section #{current_user.admin?}" 
      redirect_to signin_path
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= f.hidden_field :stripe_card_token
= f.hidden_field :tier_id
= f.hidden_field :premium
= f.hidden_field :notify_premium
= f.hidden_field :user_id
= f.hidden_field :customer_id


%fieldset
  / %legend Credit Card Stuff
  .padding-leftx
    -if @user.stripe_customer_id
      #change-card.clearfix
        %label Card
        .input
          %span
            Using card ending with
            \#{@user.stripe_customer_id}
            \#{link_to "(change)", "#"}

    %noscript
      %p This form requires Javascript to use
    #credit-card{:style => @user.stripe_customer_id ? "display:none" : "display:block"}
      #credit-card-errors{:style => "display:none"}
        #stripe-error-message.alert-message.block-message.error
      / these fields are disabled before submission and are never transmitted back to rails

    %div.xform-group
      = label_tag :credit_card_number
      = text_field_tag :credit_card_number, params[:credit_card_number], :class=>"col-lg-12 form-control", :id => "card_number", type: "text"
    .xform-group
      .col-lg-9.no-left-padding
        = label_tag :expiry_date, "Exp. Date"
        .container.no-left-padding
          .col-lg-7.no-left-padding
            = select_month nil, {:add_month_numbers => true, :use_short_month => true}, {:name => nil, :id => "card_month", :class => "form-control col-lg-7"}
          .col-lg-5.no-left-padding
            = select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+15}, {:name => nil, :id => "card_year", :class => "form-control col-lg-5"}
        /= date_select "", :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25}, {:class =>"credit-expiry inline"}
    
    
      .col-lg-3
        = label_tag :cvv, "CVV"
        = text_field_tag :cvv, params[:cvv], :class=>"col-lg-12 form-control", :id => "card_code"

    %div.xform-group
      =f.label :email
      =f.text_field :email, :validate => true, :value => (current_user ? current_user.email : ""), :class=>"form-control"
    -unless current_user
      %div.xform-group
        =label_tag :name
        =text_field_tag :name, params[:name], :class=>"form-control"
      %div.xform-group
        =label_tag :password
        =text_field_tag :password, params[:password], :class=>"form-control"

      / empty
      %span.note
      Your credit card details will be sent directly to our payment processor

app/views/transactions/_new_modal.html.haml
/ %h2#myModalLabel You need to add a credit card
/ = simple_form_for @transaction, :validate => true, :remote => true, :form => { "data-type" => "json" } do |f|
#transaction
  = simple_form_for @transaction, :validate => true, :remote => true, :form => { "data-type" => "json" } do |f|
    %div.modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      - if @transaction.errors.any?
        #error_explanation
          %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
          %ul
            - @transaction.errors.full_messages.each do |msg|
              %li= msg

    %div.modal-body
      =hidden_field_tag :post_id
    
      =render 'transactions/form', f: f
    %div.modal-footer
      = f.button :submit, name: 'Get It', class: "btn-primary", id: "new_transaction_button"
      /=link_to "Get It", nil, :class  =>"btn-primary", :id => "new_transaction_button"

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Price
    %th Tier
    %th Premium
    %th Notify premium
    %th User
    %th Customer
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.price
      %td= transaction.tier_id
      %td= transaction.premium
      %td= transaction.notify_premium
      %td= transaction.user_id
      %td= transaction.customer_id
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
/ %h2#myModalLabel You need to add a credit card
.row
  .col-lg-4
  .col-lg-4#transaction.page-element-background
    #transactionx
      -if @post
        %h3 Get this post for $#{@tier.price/100}: #{@post.title}
      
      = simple_form_for @transaction, html: {class: 'form-horizontal', role: "form"} do |f|
        - if @transaction.errors.any?
          #error_explanation
            %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
            %ul
              - @transaction.errors.full_messages.each do |msg|
                %li= msg

        =render 'form', f: f, post_id: :post_id
        %br/
    
        = f.submit "Get It", name: 'Get It', class: "btn btn-default btn-primary", id: "new_transaction_button"
        %br/
        %br/
        =link_to image_tag('solid.png', :alt => 'Stripe Payment Services'), "https://www.stripe.com/", id: "stripe_button"

app/views/transactions/new_modal.html.haml
/ %h2#myModalLabel You need to add a credit card
= simple_form_for @transaction, :validate => true, :remote => true, :form => { "data-type" => "json" } do |f|
  %div.modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    - if @transaction.errors.any?
      #error_explanation
        %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
        %ul
          - @transaction.errors.full_messages.each do |msg|
            %li= msg

  %div.modal-body
    =hidden_field_tag :post_id
    =render 'form', f: f
  %div.modal-footer
    = f.button :submit, name: 'Get It', class: "btn-primary", id: "new_transaction_button"

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Price:
  = @transaction.price
%p
  %b Tier:
  = @transaction.tier_id
%p
  %b Premium:
  = @transaction.premium
%p
  %b Notify premium:
  = @transaction.notify_premium
%p
  %b User:
  = @transaction.user_id
%p
  %b Customer:
  = @transaction.customer_id

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path